hosts:
  - localhost:8091
username: user
password: password
bucketName: dcp-test
scopeName: _default
collectionNames:
  - _default
metadataBucket: dcp-test-meta
metadataScope: _default
metadataCollection: _default
dcp:
  group:
    name: groupName
    membership:
      type: static
      memberNumber: 1
      totalMembers: 1
logging:
  level: debug
kafka:
  collectionTopicMapping:
    _default: topicname
  brokers:
    - broker1
    - broker2
  readTimeout: 30s
  writeTimeout: 30s
  producerBatchSize: 50
  producerBatchTickerDuration: 5s
  requiredAcks: 1
  #  0 -> None
  #  1 -> Gzip
  #  2 -> Snappy
  #  3 -> Lz4
  #  4 -> Zstd
  compression: 0
  # SSL configurations
  secureConnection: true
  # Config support env variable "$HOME/example/..."
  rootCAPath: "example/stretch-kafka/rootCA.pem"
  interCAPath: "example/stretch-kafka/interCA.pem"
  scramUsername: "username"
  scramPassword: "password"
